    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript">
     MathJax.Hub.Config({
         tex2jax: {
             inlineMath: [['$','$'], ['\\(','\\)']],
             processEscapes: true,
         },
         TeX: {
             Macros: {
                 RR: "{\\mathbb R}",
                 ZZ: "{\\mathbb Z}",
                 CC: "{\\mathbb C}",
                 mb: ["{\\bf #1}",1],
             }
         },
     });
    </script>
